source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa
target ‘ZSBTC’ do

pod 'SDWebImage','3.8.2'
pod 'AFNetworking', '~> 3.0.4’
pod 'JSONModel', '~> 1.2.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SVProgressHUD','~> 2.0.3'
pod 'MD5Digest', '~> 1.1.0'
pod 'MJRefresh','~> 3.1.0’
pod 'Masonry','~> 1.0.1'
pod 'RongCloudIM/IMKit', ‘2.8.0’
pod 'RongCloudIM/IMLib', '2.8.0'
pod 'FMDB','~> 2.6.2'

end
